### ISSUE TITLE
Project distribution

### ISSUE THREAD

**Issue by zeff96** [zeff96/space-travellers-hub#25]
This project has 2 assignees

## Group
1. [create API and basic setup](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204372)
2. [website header](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204373)
3. [empty profile](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204374)

## Zeff
1. [rocket display](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204376)
2. [fetch rocket data](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204380)
3. [display rocket](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204384)
4. [implement rocket booking](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204385)
5. [implement rocket booking cancellation](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204389)
6. [switch badges](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204392)
7. [display reversed rocket](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204392)

## George
1. [mission display](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204377)
2. [fetch mission data](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204377)
3. [display mission](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204377)
4. [implement mission joining](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204387)
5. [implement leaving mission](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204388)
6. [switch mission badges](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204391)
7. [display joined mission](https://github.com/users/zeff96/projects/6/views/1?pane=issue&itemId=25204395)

## Project link
[Github project link](https://github.com/users/zeff96/projects/6)

**Comment by levy002** [comment]
## Hello @zeff96 & @c00p75 

Your project is complete!  There is nothing else to say other than... Congratulations! 🎉 🎉🎉

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zeff96** [comment]
@levy002, thanks for the approval.
